version: '3.4'

services:
  azurite:
    image: "mcr.microsoft.com/azure-storage/azurite"
    container_name: "azurite-serverless-signalr-azurite"
    hostname: "azurite-serverless-signalr-azurite"
    restart: always
    ports:
      - 10000:10000
      - 10001:10001

  azure-cosmos-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    container_name: "cosmosdb-serverless-signalr-azurite"
    hostname: "cosmosdb-serverless-signalr-azurite"
    command: --protocol https
    ports:
        - 8081:8081
        - 1234:1234
        
        